name: Build Enmity and Inject Discord
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Enmity and Inject Discord
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: coreutils ldid
          cache: yes

      - name: install package.json
        id: install
        run: pnpm i

      - name: Run Main Node Script to Patch Discord
        id: build
        run: node ./index.js

      - name: Retrieve version
        id: version
        run: |
          cd ./ipas
          echo "__DISCORD_VERSION=$(ls | grep Discord | sed -e s/[^0-9.]//g | sed -e s/[/.+?\./]//g)" >> $GITHUB_OUTPUT

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: Discord_${{ steps.version.outputs.__DISCORD_VERSION }}
          title: Discord ${{ steps.version.outputs.__DISCORD_VERSION }}
          files: Dist/Discord-*_Cabin-Font+Plumpy_Icons.ipa
